<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-DD2URVG" failures="1" tests="1" name="Test1" time="8.723" errors="0" timestamp="2025-05-05T18:45:22 IST">
  <testcase classname="testCases.TC003_LoginDDT" name="verify_login" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.NullPointerException: Cannot invoke &amp;quot;org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)&amp;quot; because &amp;quot;this.row&amp;quot; is null">
      <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" because "this.row" is null
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" because "this.row" is null
at utilities.ExcelUtility.getCellData(ExcelUtility.java:62)
at utilities.DataProviders.getData(DataProviders.java:26)
... 19 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
</testsuite> <!-- Test1 -->
